from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableParallel
from dotenv import load_dotenv

load_dotenv()

model = ChatGoogleGenerativeAI(
     model="gemini-3-flash-preview"
)

parser = StrOutputParser()

notes_template = PromptTemplate(template='Generate notes from the following text. \n {text}',input_variables=['text'],validate_template=True)

quiz_template = PromptTemplate(template='Generate 5 mcqs with answers using following text. \n {text}',input_variables=['text'],validate_template=True)

merge_template = PromptTemplate(template='Merge the notes and quiz questions into one document. \n notes: {notes} \n quiz: {quiz}',input_variables=['notes','quiz'],validate_template=True)

parallel_chain = RunnableParallel(
    notes=notes_template | model | parser,
    quiz= quiz_template | model | parser
)

merging_chain = merge_template | model |  parser
final_chain = parallel_chain |  merging_chain

response = final_chain.invoke({
    'text': """
    Retrieval-Augmented Generation (RAG) is a powerful AI architecture designed to improve the quality and reliability of responses generated by large language models. Traditional language models rely only on the knowledge learned during training, which can sometimes lead to outdated or hallucinated answers. RAG solves this problem by combining retrieval systems with generative AI models. Before generating a response, the system first searches for relevant information from external data sources such as PDFs, websites, databases, or enterprise documents. The retrieved information is then provided to the language model as additional context. This allows the model to generate more accurate, context-aware, and up-to-date answers. RAG is widely used in enterprise AI assistants, document-based chatbots, research tools, and customer support systems where factual accuracy is important.

    A standard RAG pipeline consists of multiple stages that work together to process and retrieve information efficiently. First, documents are collected and loaded using document loaders. The extracted text is then split into smaller chunks using techniques such as recursive character-based or token-based chunking with overlap between chunks. These chunks are converted into vector embeddings using embedding models like OpenAI embeddings or sentence-transformers. The embeddings are stored in vector databases such as FAISS, Pinecone, ChromaDB, or Weaviate. When a user submits a query, the query is also converted into an embedding, and similarity search is performed to retrieve the most relevant chunks from the vector database. Finally, the retrieved chunks along with the user query are sent to a large language model, which generates the final context-aware response using the retrieved knowledge.
    """
}) 

print(response)

final_chain.get_graph().print_ascii()